config/routes.rb
SampleApp::Application.routes.draw do
  
  

  resources :mesajes

  resources :searches

  resources :cathegories

  resources :locations
  resources :user_acts
  resources :activities
  

  get "sessions/new"
    resources :users
    resources :sessions, :only => [:new, :create, :destroy]
    
    get 'signup' => 'users#new'
    get 'signin' => 'sessions#new'
    get 'search' => 'searches#new'
    delete 'signout' => 'sessions#destroy'
    get '/' => 'pages#home', as: 'home'
    get '/contact' => 'pages#contact'
    
    resources :activities do
        collection do
            get 'search' => 'activities#search', via: [:get, :post], as: :search
        end
    end
    

  resources :user_acts do
    member do
      post :create
    end
  end 

  resources :user_acts do
    member do
      delete :destroy
    end
  end

  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#
require 'digest'
class User < ActiveRecord::Base
  acts_as_messageable
    
  has_many :mesajes
    
    has_many :user_acts
    has_many :activities, :through => :user_acts
    
    attr_accessor :password
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates :name, :presence => true,
                     :uniqueness => true,
                     :length => { :minimum => 3, :maximum => 20}
    
    validates :email, :presence => true,
                      :format => { :with => email_regex }
    
    validates :password, :presence => true,
                         :confirmation => true,
                         :length => { :within => 3..40 }
    
    before_save :encrypt_password
    
    def has_password?(submitted_password)
        encrypted_password == encrypt(submitted_password)
    end
    
    def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
    end

def self.authenticate(email, submitted_password)
user = find_by_email(email)
return nil  if user.nil?
return user if user.has_password?(submitted_password)
end

def self.authenticate_with_salt(id, cookie_salt)
user = find_by_id(id)
(user && user.salt == cookie_salt) ? user : nil
end


private

    def encrypt_password
        self.salt = make_salt if new_record?
        self.encrypted_password = encrypt(password)
    end
    
    def encrypt(string)
        secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
        secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
        Digest::SHA2.hexdigest(string)
    end
    
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy, :correct_user]
    before_filter :authenticate, :only => [:edit, :update, :destroy, :index]
    before_filter :correct_user, :only => [:edit, :update, :destroy]
    before_filter :admin_user, :only => [:user_params_admin]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      @title = "Inscription"
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if admin_user?
      if @user.update(user_params_admin)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    else
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # DELETE /users/1
  # DELETE /users/1.json
    # DELETE /users/1.json
    def destroy
        UserAct.all.each do |ua|
          if ua.id_user == @user.id
            ua.destroy
          end
        end

        Activity.all.each do |aa|
          if aa.id_creator == @user.id
            aa.destroy
          end
        end

        @user.destroy
        respond_to do |format|
            format.html { redirect_to users_url }
            format.json { head :no_content }
        end
    end

  

  private
    
   
    
    def correct_user
        redirect_to(home_path) unless current_user?(@user) or admin_user?
    end
            
   
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def admin_user?
      current_user.name == "administrator"
    end
    
    def admin_user
      !admin_user?
    end
    
    def user_params_admin
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
  
  def admin_situation?(user)
    if user.admin == "true"
      return true
    else
      return false
    end
  end
  
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, :class => "field_title" %>
    <%= f.text_field :name, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :email, :class => "field_title" %>
    <%= f.text_field :email, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :password, :class => "field_title" %>
    <%= f.password_field :password, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confimation", :class => "field_title" %>
    <%= f.password_field :password_confirmation, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit "Ready" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
     </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Go to this profile', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="form_title">Join the community</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="bloc">
  <div class="name">
  <strong> Welcome to you <br><span id="profile_name"><%= @user.name %></span></strong>
  </div>
  
 <article class="info">
    <p><%= @user.email %> | <%= link_to "Friends", '#'%> | <%= link_to "Activities", activities_path %> |
	  <%= "Admin Situation:" "#{@user.admin}" %>
	
       </p>
  </article>
  
  <article class="profileaside">
  <p> <%= link_to 'Edit Profile', edit_user_path(@user) %></p>
  <p>    <%= link_to 'Users', users_path %></p>
  <p>	<%= link_to 'Current Events', activities_path %></p>
  <p> <%= link_to 'Delete account', @user, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  
  </article>
  

<going>
  <div>
    <% 
    @count = 0
    @target = nil
    @usacts = UserAct.all 
        @usacts.each do |f|
          if f.id_user == @user.id %>
            <% @target = Activity.find(f.id_activity)
            if @target != nil 
              if @count ==0 %>
                <strong><%= "#{@user.name}" %> is going to these events:</strong>
                <% @count = 1%>
            <% end
            end%>
              <p>
                <%= link_to "#{@target.name}", activity_path(@target.id) %>
              </p>
            <% 
          end  
        end%>
  </div>
</going>
</div>