config/routes.rb
SampleApp::Application.routes.draw do
  
  

  resources :mesajes

  resources :searches

  resources :cathegories

  resources :locations
  resources :user_acts
  resources :activities
  

  get "sessions/new"
    resources :users
    resources :sessions, :only => [:new, :create, :destroy]
    
    get 'signup' => 'users#new'
    get 'signin' => 'sessions#new'
    get 'search' => 'searches#new'
    delete 'signout' => 'sessions#destroy'
    get '/' => 'pages#home', as: 'home'
    get '/contact' => 'pages#contact'
    
    resources :activities do
        collection do
            get 'search' => 'activities#search', via: [:get, :post], as: :search
        end
    end
    

  resources :user_acts do
    member do
      post :create
    end
  end 

  resources :user_acts do
    member do
      delete :destroy
    end
  end

  

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'This is what we found:' }
        format.json { render action: 'show', status: :created, location: @search }
      else
        format.html { render action: 'new' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:actname, :locname, :creator, :catname)
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :actname, :class => "field_title" %><br>
    <%= f.text_field :actname, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :locname, :class => "field_title" %><br>
    <%= f.text_field :locname, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :creator, :class => "field_title" %><br>
    <%= f.text_field :creator, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :catname, :class => "field_title" %><br>
    <%= f.text_field :catname, :class => "blank" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<h1>Listing searches</h1>

<table>
  <thead>
    <tr>
      <th>Actname</th>
      <th>Locname</th>
      <th>Creator</th>
      <th>Catname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.actname %></td>
        <td><%= search.locname %></td>
        <td><%= search.creator %></td>
        <td><%= search.catname %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Results: </h1>

<%@countname =0%>

<p>
  <!--first we search activity name -->
  <% if @search.actname!=""%>
    <p>Matches under name "<%=@search.actname%>"</p>
  <%end%>
  <% 
  	  @zero=0
	  @acts=Activity.all
	  @acts.each do |a|
	  		if @search.actname != ""
		  		if a.name == @search.actname
		  			@countname+=1
		  			%>
		  			<p>
		  				<%= link_to "#{a.name}", activity_path(a.id) %>
		  			</p>
		  			<%
		  		end
		  	else
		  		if @zero==0
			  		%>
			  			<p>No activity name provided.</p>
			  		<%
			  		@zero=1	
		  		end			
	  		end
	  	end
  %>
</p>

<p>-----------------------------------------------------------------------------</p>

<p>
 <!--now we find under location name-->
 <% if @search.locname!=""%>
 <p>Matches under location "<%=@search.locname%>"</p>
 <%end%>
 	<% 
 	  @zero=0
	  @locs=Location.all
	  @locs.each do |l|
	  		if @search.locname != ""
		  		if l.name == @search.locname
		  			@acts=Activity.all
		  			@acts.each do |a|
			  			if a.id_location == l.id
				  			@countname+=1
				  			%>
				  			<p>
				  				<%= link_to "#{a.name}", activity_path(a.id) %>
				  			</p>
				  			<%
			  			end
		  			end
		  		end
		  	else
		  		if @zero==0
			  		%>
			  			<p>No location name provided.</p>
			  		<%
			  		@zero=1	
		  		end	
	  		end
	  	end
  %>
</p>

<p>-----------------------------------------------------------------------------</p>

<p>
 <!--now we find under creator name-->
 <% if @search.creator!=""%>
 <p>Matches under creator "<%=@search.creator%>"</p>
 <% end %>
 	<% 
 	  @zero=0
	  @uss=User.all
	  @uss.each do |u|
	  		if @search.creator != ""
		  		if u.name == @search.creator
		  			@acts=Activity.all
		  			@acts.each do |a|
			  			if a.id_creator == u.id
				  			@countname+=1
				  			%>
				  			<p>
				  				<%= link_to "#{a.name}", activity_path(a.id) %>
				  			</p>
				  			<%
			  			end
		  			end
		  		end
		  	else
		  		if @zero==0
			  		%>
			  			<p>No user name provided.</p>
			  		<%
			  		@zero=1	
		  		end	
	  		end
	  	end
  %>
</p>

<p>-----------------------------------------------------------------------------</p>

<p>
 <!--now we find under cathegory name-->
 <% if @search.catname!=""%>
 <p>Matches under cathegory "<%=@search.catname%>"</p>
 <%end%>
 	<% 
 	  @zero=0
	  @cat=Cathegory.all
	  @cat.each do |c|
	  		if @search.catname != ""
		  		if c.name == @search.catname
		  			@acts=Activity.all
		  			@acts.each do |a|
			  			if a.id_cathegory == c.id
				  			@countname+=1
				  			%>
				  			<p>
				  				<%= link_to "#{a.name}", activity_path(a.id) %>
				  			</p>
				  			<%
			  			end
		  			end
		  		end
		  	else
		  		if @zero==0
			  		%>
			  			<p>No user name provided.</p>
			  		<%
			  		@zero=1	
		  		end	
	  		end
	  	end
  %>
</p>

<strong> We found <%=@countname%> results under given criteria. </strong>
<p>
<%= link_to 'Back', activities_path %>
</p>