config/routes.rb
SampleApp::Application.routes.draw do
  
  

  resources :mesajes

  resources :searches

  resources :cathegories

  resources :locations
  resources :user_acts
  resources :activities
  

  get "sessions/new"
    resources :users
    resources :sessions, :only => [:new, :create, :destroy]
    
    get 'signup' => 'users#new'
    get 'signin' => 'sessions#new'
    get 'search' => 'searches#new'
    delete 'signout' => 'sessions#destroy'
    get '/' => 'pages#home', as: 'home'
    get '/contact' => 'pages#contact'
    
    resources :activities do
        collection do
            get 'search' => 'activities#search', via: [:get, :post], as: :search
        end
    end
    

  resources :user_acts do
    member do
      post :create
    end
  end 

  resources :user_acts do
    member do
      delete :destroy
    end
  end

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :mesajes
    has_many :user_acts
	has_many :users, :through => :user_acts
    belongs_to :cathegory
    belongs_to :location
    
    
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
    before_action :set_activity, :only => [:show, :edit, :update, :destroy, :set_user]
  before_filter :authenticate, :only => [:edit, :update, :destroy, :index]
  before_filter :correct_user, :only => [:edit, :update, :destroy]
    before_action :set_user, :only => [:correct_user, :show]
     respond_to :html

  # GET /activities
  # GET /activities.json
  def index
      
    @activities = Activity.all
    @user = current_user
      
      @search = Activity.search(params[:name])
      @users = params[:distinct].to_i.zero? ?
      @search.result :
      @search.result(distinct: true)
      
      respond_with @users
  end
 
  def search
      index
      render :index
      
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @mesaje = Mesaje.new
    @mesaje.id_creator = current_user.id
    @mesaje.id_activity = @activity.id
   
    
  end

  def unite
      @activity.user_act.new#(id_activity: @activity[:id], id_user: current_user[:id])
      respond_to do |format|
      if @user_act.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
   @activity  = Activity.new(activity_params)
      @activity.id_creator = current_user[:id]
      
       respond_to do |format|
      if @activity.save
        
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    UserAct.all.each do |ua|
      if ua.id_activity == @activity.id
        ua.destroy
      end
    end

    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  private
    
    def correct_user
        redirect_to(home_path) unless current_user.id == @activity.id_creator or admin_user?
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
      @idmes = @activity.id
    end
    
    def admin_user?
      current_user.name == "administrator"
    end
    
    def set_user
        @user = User.find_by_id(@activity.id_creator)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:id_location, :name, :date, :duration, :id_cathegory, :description, :privacy, :accepted)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
    
    def name_createur(activity)
        return User.find_by_id[:activity.creator_id][:name]
        end
    
    def model_fields
        # which fields to display and sort by
        [:name, :id_location]
    end
    
    def results_limit
        # max number of search results to display
        10
    end
    
    def display_query_sql(users)
        "SQL: #{users.to_sql}"
    end
    
    def display_results_header(count)
        if count > results_limit
            "Your first #{results_limit} results out of #{count} total"
            else
            "Your #{pluralize(count, 'result')}"
        end
    end
    
    def action
        action_name == 'advanced_search' ? :post : :get
    end
    
    def display_sort_column_headers(search)
        model_fields.each_with_object('') do |field, string|
            string << content_tag(:th, sort_link(search, field, {}, method: action))
        end
    end
    
    def display_search_results(objects)
        objects.limit(results_limit).each_with_object('') do |object, string|
            string << content_tag(:tr, display_search_results_row(object))
        end
    end
    
    def display_search_results_row(object)
        model_fields.each_with_object('') do |field, string|
            string << content_tag(:td, object.send(field))
        end
        .html_safe
    end
    

end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
    <%= f.label :id_location, :class => "field_title" %><br>
    <%= f.number_field :id_location, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :name, :class => "field_title" %><br>
    <%= f.text_field :name, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :date, :class => "field_title" %><br>
    <%= f.text_field :date, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :duration, :class => "field_title" %><br>
    <%= f.text_field :duration, :class => "blank" %> <!-- display list -->
  </div>
  <div class="field">
    <%= f.label :id_cathegory, :class => "field_title" %><br>
    <%= f.number_field :id_cathegory, :class => "blank"%>
  </div>
  <div class="field">
    <%= f.label :description, :class => "field_title" %><br>
    <%= f.text_area :description, rows: 15, cols: 80, :class => "blank" %>
  </div>
  <div class="field">
    <%= f.label :privacy, :class => "field_title" %><br>
    <%= f.check_box :privacy %>
  </div>
  <% if current_user.name == "administrator" %>
  <div class="field">
    <%= f.label :accepted, :class => "field_title" %><br>
    <%= f.check_box :accepted %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/_results.html.erb
<%= content_tag :p, display_query_sql(@users) %>
<%= content_tag :h2, display_results_header(@users.size) %>
<%= content_tag :table do %>
  <%= content_tag :thead, display_sort_column_headers(@search), nil, false %>
  <%= content_tag :tbody, display_search_results(@users), nil, false %>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<% @activities.each do |activity| %>
<div>
<aside class="index_aside">
    <p><%= activity.date %></p>
	<p><%= activity.duration %></p>
	
</aside>

<article class="index_article">
	<h2><%= activity.name %></h2>
	<p><%@loc = Location.find_by_id(activity.id_location)%><%= @loc.name %></p>
	<p> Created by <%@uss = User.find_by_id(activity.id_creator)%><%= @uss.name %></p>
	  
     <p> <%= link_to 'Show', activity %> |
        <%= link_to 'Edit', edit_activity_path(activity) %> |
        <%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </article>
  </div>

    <% end %>

 

<br>

<%= link_to 'Create your activity !', new_activity_path %> <br>

app/views/activities/new.html.erb
<div class="formbox">
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

</div>

app/views/activities/search.html.erb
<%= search_form_for @q url: search_people_path,
                        html: { method: :post } do |f| %>
  <%= f.label :id_location %>
  <%= f.number_field :id_location %>
  
  <%= f.submit %>
<% end %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @activity.name %>
</h1>


 
  
  <p><strong>Accepted:</strong>
  <%= @activity.accepted %>
  </p>


<creator>by 
  <%@user=User.find_by_id(@activity.id_creator) %>
  <%= link_to "#{@user.name}", user_path(@user.id) %>
</creator>
<p>
  <strong>Location:</strong>
  <%@loc = Location.find_by_id(@activity.id_location)%>
  <%= link_to "#{@loc.name}", location_path(@loc.id) %>
</p>

<p>
  <strong>Date:</strong>
  <%= @activity.date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @activity.duration %>
</p>

<p>
  <strong>Cathegory:</strong>
  <%@cat = Cathegory.find_by_id(@activity.id_cathegory)%>
  <%= link_to "#{@cat.name}", cathegory_path(@cat.id) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<p>
  <strong>Privacy:</strong>
  <%= @activity.privacy %>
</p>

<invited>
  <div>
    <% 
    @count = 0
    @icount = 0
    @target = nil
    @usacts = UserAct.all 
        @usacts.each do |kaze|
          if kaze.id_activity == @activity.id
            @icount+=1
          end
        end
        @usacts.each do |f|
          if f.id_activity == @activity.id %>
            <% @target = User.find(f.id_user)
            if @target != nil 
              if @count ==0 %>
                <strong>People who're going (<%=@icount%>)</strong>
                <% @count = 1%>
            <% end
            end%>
              <p>
                <%= link_to "#{@target.name}", user_path(@target.id) %>
              </p>
            <% 
          end  
        end%>
  </div>
</invited>

<%= link_to 'Edit', edit_activity_path %> |
<%= link_to 'Back', activities_path %>

<p>
  <%= notRepeated = true
    @thisUser=nil
    @user_acts=UserAct.all
    @user_acts.each do |e|
      if current_user[:id] == e.id_user
        if @activity[:id] == e.id_activity
          @thisUser=e
          notRepeated = false
        end
      end
    end
    if notRepeated then
      button_to 'Going!', user_acts_path(:id_activity => @activity[:id], :id_user => current_user[:id])
    else
      button_to 'Not Going',@thisUser, method: :delete, data: { confirm: 'Are you sure?' }

    end
  %>

  <!-- <%=button_to 'Going!', user_acts_path(:id_activity => @activity[:id], :id_user => current_user[:id]) %> -->
</p>
<h1>Forum about this activity</h1>

<table>

  <thead>
	  <%@mes = Mesaje.where(id_activity: @activity.id)%>
      <% @mes.each do |mesaje| %>
	  <% @creator = User.find_by_id(mesaje.id_creator)%>
    <tr>
      <th>By <%= @creator.name%></th>
	  <th class="description">Message</th>
    </tr>
  </thead>
  <tbody>
	  <tr>
		<td>Title <%= mesaje.title %></td>
        <td class="description"><%= mesaje.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= form_for(@mesaje) do |f| %>
  <% if @mesaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mesaje.errors.count, "error") %> prohibited this mesaje from being saved:</h2>

      <ul>
      <% @mesaje.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :id_activity %><br>
    <%= f.number_field :id_activity%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>