config/routes.rb
SampleApp::Application.routes.draw do
  
  

  resources :mesajes

  resources :searches

  resources :cathegories

  resources :locations
  resources :user_acts
  resources :activities
  

  get "sessions/new"
    resources :users
    resources :sessions, :only => [:new, :create, :destroy]
    
    get 'signup' => 'users#new'
    get 'signin' => 'sessions#new'
    get 'search' => 'searches#new'
    delete 'signout' => 'sessions#destroy'
    get '/' => 'pages#home', as: 'home'
    get '/contact' => 'pages#contact'
    
    resources :activities do
        collection do
            get 'search' => 'activities#search', via: [:get, :post], as: :search
        end
    end
    

  resources :user_acts do
    member do
      post :create
    end
  end 

  resources :user_acts do
    member do
      delete :destroy
    end
  end

  

end

app/views/layouts/_header.html.erb
<header>
<nav class="logo">
  <p> <span class="campus"> CampUS </span>  <%= link_to "Whats hot", activities_path %> </p>
</nav>
  
<nav class="banner">
   <ul>
      <li><%= link_to "Home", home_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Search", new_search_path %></li>
        <li><%= link_to "#{current_user.name}\'s Profile", current_user %></li>
        <li><%= link_to "Create Activity", new_activity_path %><li>
      <% end %>
      <li><%= link_to "Help", '#' %></li>
      <% if signed_in? %>
      <li><%= link_to "Logout", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign In", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
 <!--[if lt IE 9]>
   <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
   <![endif]--> 
 <%= csrf_meta_tags %>
 <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
 <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
 <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
   <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= cool %></title>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= render 'layouts/stylesheets' %>
 </head>

<body>
<div class="container">
	<%= render 'layouts/header'%>
	
	<nav id="homenav">
	 <% if signed_in? %>
	      <li><%= link_to "Activities", activities_path %></li>
	      <li><%= link_to "Users", users_path %></li>
	      <li><%= link_to "Places", locations_path %></li>
	      <li><%= link_to "Cathegories", cathegories_path %></li>
		  <% end %>
	 </nav>
<section class="round">
<%= yield %>
</section>
</div>
</body>	 	
</html>